### ISSUE TITLE
After Format, Xcode scroll the code automatically, then the selected text has been invisable

### ISSUE THREAD

**Issue by harrayhu** [mapbox/XcodeClangFormat#11]
The selected code scroll down every time after be formatted, I must scroll back to reach the previous position.
Is this a bug?

**Comment by kkaefer** [comment]
I've observed this as well, and I'm not sure whether this is an Xcode bug or related to this extension. Overall, all this extension does is to change the contents of the code, but it looks like Xcode somehow doesn't maintain the scroll position.

**Comment by kkaefer** [comment]
I changed the way changes are applied in the new release, which is available at https://github.com/mapbox/XcodeClangFormat/releases/tag/v1.1.0. This should now be fixed.
