### ISSUE TITLE
Webkit - adds d 

### ISSUE THREAD

**Issue by JulesMoorhouse** [mapbox/XcodeClangFormat#17]
If you use the webkit setting on an objective c m file, it adds a "d" at the end of the file.

**Comment by kkaefer** [comment]
I changed the way changes are applied in the new release, which is available at https://github.com/mapbox/XcodeClangFormat/releases/tag/v1.1.0. Source code type is now recognized as well and different clang-format settings can be applied to Objective-C vs. C++ source.
