### ISSUE TITLE
XcodeClangFormat OX10.11 ERROR:'clang/Format/Format.h' file not found

### ISSUE THREAD

**Issue by xavierXing** [mapbox/XcodeClangFormat#19]
According to the tutorial I installed the plugin but when I compile the questions:

'clang/Format/Format.h' file not found

My MAC OS x 10.11 is 8.2.1 Xcode versionPlease help me thank you

**Comment by kpdev** [comment]
Same thing. Anybody?

**Comment by SimonGoodwin** [comment]
Same here. Trying to build Clang-format for Xcode 9.2 on MacOS 10.13.6

**Comment by martinfinke** [comment]
My version works with Xcode 10: https://github.com/martinfinke/XcodeClangFormat

**Comment by kkaefer** [comment]
To compile yourself, you need to run `./configure` as mentioned in the FAQ.
