### ISSUE TITLE
unable to build: code signing fails

### ISSUE THREAD

**Issue by philXYZ1** [mapbox/XcodeClangFormat#2]
Hi there,

after cloning the repo and running the configure script, 
building fails for me with the follwing errors:

None of your accounts are a member of 'GJZR2MEM28':  An unexpected error occurred. Xcode cannot find a team matching 'GJZR2MEM28'.

No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "GJZR2MEM28" with a private key was found.

Switching to my Team in the General Settings tab does not change anything.
Automatically manage signing is activated. 
Disabling this setting and setting the team for the debug and release builds manually, has no effect as well.

any ideas? (I'm running XCode 8)

**Comment by kkaefer** [comment]
Did you switch both targets to your Team/ID?

**Comment by philXYZ1** [comment]
Yes I did, the error persists. Provisioning Profile is set to None.

**Comment by rmont881** [comment]
I ran into this as well. Changing both XcodeClangFormat and clang-format targets to my personal team and a Product->Clean fixed it for me.

**Comment by Slyv** [comment]
@philXYZ1 Better don't set Provisioning Profile to None. You have to generate Mac Developmenet provisioning profile and set it to "Provisioning Profile" in Xcode. If you have it generated, check in developer.apple.com if it is still valid (not expired).

**Comment by philXYZ1** [comment]
Thanks for the help, got it to work by setting both targets to my Team, I somehow missed that setting.
