### ISSUE TITLE
Empty lines appended at the bottom sometimes.

### ISSUE THREAD

**Issue by pres** [mapbox/XcodeClangFormat#21]
It's really hard to reproduce but sometimes using clang-format on a source file or reverting the formatting with `cmd+z` appends new empty lines at the bottom of the file.

**Comment by rggjan** [comment]
Also, sometimes at the top...

**Comment by kkaefer** [comment]
I changed the way changes are applied in the new release, which is available at https://github.com/mapbox/XcodeClangFormat/releases/tag/v1.1.0. This bug should now be fixed.
