### ISSUE TITLE
Can't get this working on 10.13.3

### ISSUE THREAD

**Issue by DougBanksPersonal** [mapbox/XcodeClangFormat#24]
Tech support people forced me to upgrade to 10.13.3. Since then this plugin stopped working.

Specifically, when I go to System Preferences -> Extensions, there is no "Xcode Source Editor" option.

I tried the solution from jehnes here:
https://github.com/mapbox/XcodeClangFormat/issues/1

And get blocked because I can't build:
None of your accounts are a member of 'GJZR2MEM28':  An unexpected error occurred. Xcode cannot find a team matching 'GJZR2MEM28'.
No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "GJZR2MEM28" with a private key was found.

**Comment by hansgans** [comment]
Same problem here.

**Comment by EgorVeremeychik** [comment]
+1

**Comment by sean-parent** [comment]
I took another approach - commenting here to help anyone else who was stuck. https://github.com/sean-parent/tools/

**Comment by kkaefer** [comment]
@DougBanksPersonal This is an issue related to code signing. Please check "manage code signing automatically" and retry.
