### ISSUE TITLE
macOS hight sierra cannot load extionsion auto

### ISSUE THREAD

**Issue by cjckkk** [mapbox/XcodeClangFormat#26]
before i user noramal
today i update to macos hight sierra 10.13.6
extension menu not show up
cannot use anymore

**Comment by kkaefer** [comment]
Did you try relaunching the application?

**Comment by cjckkk** [comment]
try many time
i guess it cause by new version macos 10.13.6

**Comment by kkaefer** [comment]
I am running Xcode 10 on macOS 10.13.4 and XcodeClangFormat works as intended (even without restarting). Can you please provide further details into _what_ is going wrong on your system? e.g. error logs, error messages etc.

**Comment by cjckkk** [comment]
i use normal on the macos 10.13.5
extension menu no show up the XcodeClangFormat when i update to the 10.13.6
the application is  open as usually

**Comment by masakapa** [comment]
<img width="668" alt="wx20181008-151537 2x" src="https://user-images.githubusercontent.com/6830671/46595926-26287880-cb0d-11e8-8921-988a5355c499.png">
