### ISSUE TITLE
Which version of clang-format is used ?

### ISSUE THREAD

**Issue by MartyLake** [mapbox/XcodeClangFormat#27]
Hello,
I don't have a mac right now but I was wondering: which version of clang-format is used for this extension ? Is it possible to replace the binary somewhere with the desired version (8.0) ?
Best

**Comment by martinfinke** [comment]
It looks like [3.9.0](https://github.com/mapbox/XcodeClangFormat/blob/master/configure#L7) is used. I've just made some minor changes so it works with LLVM 8.0.0. Please let me know if you're still interested and I'll create a public fork.

**Comment by MartyLake** [comment]
Still interested :D

**Comment by martinfinke** [comment]
👍Let me know if the link above compiles and works fine.

**Comment by shixiaoda** [comment]
> It looks like [3.9.0](https://github.com/mapbox/XcodeClangFormat/blob/master/configure#L7) is used. I've just made some minor changes so it works with LLVM 8.0.0:
> 
> https://github.com/martinfinke/XcodeClangFormat

Can you release a new version precompiled  app ? Download llvm 8.0 is too slow ...

**Comment by kkaefer** [comment]
https://github.com/mapbox/XcodeClangFormat/releases/tag/v1.1.0 now uses the most recent LLVM/Clang 10.
