### ISSUE TITLE
Using a dumped .clang-format file returns "Could not parse custom style: invalid argument"

### ISSUE THREAD

**Issue by matteomatassoni** [mapbox/XcodeClangFormat#29]
I've tried both with:
- `clang-format -style=WebKit -dump-config > .clang-format`
- `clang-format -style=llvm -dump-config > .clang-format`

on clang-format version 8.0.0
Do you have any hint?

**Comment by kkaefer** [comment]
https://github.com/mapbox/XcodeClangFormat/releases/tag/v1.1.0 now uses LLVM/Clang 10. Could you please retry? The new version should be able to read current .clang-format files.
