### ISSUE TITLE
unable to build: #import <clang/Format/Format.h>

### ISSUE THREAD

**Issue by dollar2048** [mapbox/XcodeClangFormat#3]
on line:
`#import <clang/Format/Format.h>`

I've got:
Lexical or Preprocessor Issue Group:

`.../XcodeClangFormat-master/clang-format/ClangFormatCommand.mm:5:9: 'clang/Format/Format.h' file not found`

What shall I do?
Thanks.

**Comment by kkaefer** [comment]
Did you follow the [`Building` guide in the Readme](https://github.com/mapbox/XcodeClangFormat#building) and run `./configure`?
