### ISSUE TITLE
breakpoints are clear after format

### ISSUE THREAD

**Issue by water-in-stone** [mapbox/XcodeClangFormat#33]
Breakpoints are clear after format.

By the way, My Xcode version is : 11.3.1 (11C504)

**Comment by kkaefer** [comment]
I changed the way changes are applied in the new release, which is available at https://github.com/mapbox/XcodeClangFormat/releases/tag/v1.1.0. Breakpoints are still cleared when the breakpoint is within the changed text, but other breakpoints should now persist across formatting.
