### ISSUE TITLE
v1.1 crashes with custom format

### ISSUE THREAD

**Issue by rggjan** [mapbox/XcodeClangFormat#34]
Using this custom format file:
```
BasedOnStyle: Webkit
ColumnLimit: 120
```
Running clang-format in Xcode I get the following error:
<img width="281" alt="Screenshot 2020-05-24 at 15 36 37" src="https://user-images.githubusercontent.com/128554/82755551-82203d80-9dd4-11ea-9c12-76b4993ac887.png">
and the attached clang-format crash.

[clang-format-crash.txt](https://github.com/mapbox/XcodeClangFormat/files/4673603/clang-format-crash.txt)

**Comment by rggjan** [comment]
v1.0 worked fine...

**Comment by kkaefer** [comment]
I don't think this is related to the custom format file, but rather to an error in how the new version applies the format changes. This is typically dependent on the actual code being formatted. Can you share the code, or preferably a minimal example that reproduces this crash? It can also be dependent the text you have selected when formatting the code, so if it only happens for some selections, please also let me know what text you have selected.

**Comment by rggjan** [comment]
Interesting, it seems to crash whenever I format something in a `.mm` or `.m` file. Formatting the same code in a `.cpp` or `.h` file works fine!

Also, formatting any of these files with a predefined style like `LLVM` works fine. However, as soon as I use a custom `.clang-format` file on `.mm` or `.m` it crashes...

This happens with any code as simple as this:
```
void foo() {  
}
```

**Comment by michael75431** [comment]
Same exact problem.   The custom file that's worked for years works on .h but not .m files as of 1.1

**Comment by kkaefer** [comment]
@rggjan, @michael75431: I pushed a fix in https://github.com/mapbox/XcodeClangFormat/issues/34. Here's a build with that fix applied: 
[XcodeClangFormat.zip](https://github.com/mapbox/XcodeClangFormat/files/4802645/XcodeClangFormat.zip). Could you please confirm that your custom `.clang-format` file now works? If it doesn't, could you please post the contents of that file?

**Comment by rggjan** [comment]
Awesame, thanks @kkaefer ! Just tested the zip, and it seems to work without problems :) 👍
