### ISSUE TITLE
Bad formatting if .cc file starts // style comments

### ISSUE THREAD

**Issue by anktkr** [mapbox/XcodeClangFormat#42]
Steps to redo: 
- Select formatting style to be Mozilla. Just to be consistent. 
- Create a new Xcode project, template C++.
- Format it with "format entire file". 

The original file contents are 
```c++
//
//  main.cpp
//  testtttt

#include <iostream>

int main(int argc, const char * argv[]) {
  // insert code here...
  std::cout << "Hello, World!\n";
  return 0;
}
```
After formatting:
```diff
 #include <iostream>
 
-int main(int argc, const char * argv[]) {
+int
+ain(int argc, const char  argv[])
+
   // insert code here...
   std::cout << "Hello, World!\n";
   return 0;
```
Now undo the formatting changes, remove all the `//` comments from the start, and format again. It's correct now. 
```diff
-//
-//  main.cpp
-//  testtttt

 #include <iostream>
 
-int main(int argc, const char * argv[]) {
+int
+main(int argc, const char* argv[])
+{
   // insert code here...
   std::cout << "Hello, World!\n";
   return 0;
```

**Comment by kkaefer** [comment]
I can't reproduce this issue with the most recent version (1.2). Could you please verify that you're using that version? The previous version 1.1. had an issue similar to this one related to non-ASCII characters.

**Comment by anktkr** [comment]
Oh I didn't realise that there was a newer version available. Downloaded 1.2 and can confirm it works perfectly.

**Comment by anktkr** [comment]
> can confirm it works perfectly.
I spoke a bit too early... standard styles work great, (the bug reported here is not present either). But it does nothing if custom  style is used. 
Let me file a new report with the required files.
