### ISSUE TITLE
 No debug symbols in crash reports of the app.

### ISSUE THREAD

**Issue by anktkr** [mapbox/XcodeClangFormat#43]
The formatter fails to format a normal file a few times every day. Solution is to tinker around in the navigator till it finally works.

I noticed that Console.app has several crash logs of XcodeClangFormat app but they're not useful due to the lack of debug symbols. Adding them to the app could help the developer collect useful data to fix bugs.

**Comment by kkaefer** [comment]
@anktkr I'm happy to accept the crashlogs even if they're unsymbolicated. What version of the app are you using?

**Comment by anktkr** [comment]
Here:
[clang_format_crash_logs#43.zip](https://github.com/mapbox/XcodeClangFormat/files/4923442/clang_format_crash_logs.43.zip)

Version is `Version 1.1 (1)`

**Comment by kkaefer** [comment]
Thanks! Given that this is still with 1.1, I won't investigate this further, since 1.2 fixed a lot of crashes.
