### ISSUE TITLE
Add menu item for formatting the entire file

### ISSUE THREAD

**Issue by kkaefer** [mapbox/XcodeClangFormat#5]
Right now, only the selected code (and possibly the surrounding lines/block) are formatted.

**Comment by wellswong1990** [comment]
'clang/Format/Format.h' file not found show in my xCode 8
![snip20161008_2](https://cloud.githubusercontent.com/assets/20511068/19209612/96c2cb20-8d40-11e6-8ec0-646886888ebc.png)

**Comment by kkaefer** [comment]
@wellswong1990 please don't hijack a completely unrelated thread. You can find information about building in the Readme: https://github.com/mapbox/XcodeClangFormat#building

**Comment by kkaefer** [comment]
Added in https://github.com/mapbox/XcodeClangFormat/releases/tag/v1.1.0.
