### ISSUE TITLE
Can't apply formatting to c++ header files

### ISSUE THREAD

**Issue by corporate-fun** [mapbox/XcodeClangFormat#51]
I'm trying to apply the formatting to c++ header files that have file extensions .h and I keep getting an error that says "Could not parse custom style: Invalid argument." in Xcode.

Applying the formatting to .cpp files does work.

I'm using Xcode version 11.6 on macOS 10.15.5

This is my clang-format file (the. name of the file in the project is actually `_clang-format`):
[_clang-format.txt](https://github.com/mapbox/XcodeClangFormat/files/5132902/_clang-format.txt)

**Comment by kkaefer** [comment]
I believe this is fixed with https://github.com/mapbox/XcodeClangFormat/pull/52
