### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by hamaney** [mapbox/XcodeClangFormat#7]
Please, can you add the steps of uninstalling XcodeClangFormat to the Readme ? thanks

**Comment by KevinArturia** [comment]
I have the same request. Since I have installed it I have a problem with Xcode, the Comment/Uncomment shortcut does not work anymore. So i'd like to uninsntall it to check if it is the source of the problem.

**Comment by kkaefer** [comment]
You'll just have to trash the .app bundle.

**Comment by kkaefer** [comment]
You'll just have to trash the .app bundle.

**Comment by kkaefer** [comment]
You'll just have to trash the app bundle.

**Comment by kkaefer** [comment]
You'll just have to trash the app bundle.

**Comment by anktkr** [comment]
> So i'd like to uninsntall it to check if it is the source of the problem.

Or disable it in System Preferences > Extensions.
