### ISSUE TITLE
when set custom style file no work help me! how to do 

### ISSUE THREAD

**Issue by jsonwang** [mapbox/XcodeClangFormat#8]
when set custom style file no work help me! how to do 
- (NSData_)tryCreateBookmarkFromURL:(NSURL_)url {
  // Create a bookmark and store into defaults.
  NSError\* error = nil;
  NSData \* dddd = [url bookmarkDataWithOptions:NSURLBookmarkCreationWithSecurityScope |
                   NSURLBookmarkCreationSecurityScopeAllowOnlyReadAccess
                includingResourceValuesForKeys:nil
                                 relativeToURL:nil
                                         error:&error];
  
  NSLog(@"this is error: %@",error);
  
  return dddd;

}
Error Domain=NSCocoaErrorDomain Code=256 "Could not open() the item" UserInfo={NSURL=file:///Users/ak/Desktop/12345/clang-format, NSDebugDescription=Could not open() the item}

**Comment by jsonwang** [comment]
i confirm file is exist

**Comment by kkaefer** [comment]
To use a custom clang-format style, open the app itself and select the file there. Due to sandboxing restrictions, clang-format can't read arbitrary files on the file system. Instead, you can give the extension explicit permission to open a .clang-format file by selecting it in the app.
